---
- hosts: vinhserver
  remote_user: ubuntu
  become: true

  tasks:
    - name: Ansible copy file to remote server
      copy:
        src: /home/mrlinh/Documents/0.Vinh_Project/nginx
        dest: /home/ubuntu/fpt
    - name: Ansible copy file to remote server
      copy:
        src: /home/mrlinh/Documents/0.Vinh_Project/docker-compose.yml
        dest: /home/ubuntu/fpt


